baseURL: https://andytbeck.com
languageCode: en
DefaultContentLanguage: en
title: Website of Andy Beck
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Andy Beck
  customCss: []
  customJs: []
  description: Biostatistician, Hobby Jogger, Goofball
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: yes
    use: katex
  profilePicture: images/profile2.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-strava
      title: instagram
      url: https://www.strava.com/athletes/25469722
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/theandyb
    - icon: fab fa-instagram
      title: Instagram
      url: https://www.instagram.com/abeck90/
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/andytbeck/
  title: Meet Andy B.
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
taxonomies:
  series: series
